# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('bio', models.TextField(max_length=1000)),
                ('thumbnail', models.TextField(max_length=300)),
                ('character_id', models.IntegerField()),
                ('is_popular', models.BooleanField(default=False)),
                ('is_stale', models.BooleanField(default=True)),
                ('etag', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(max_length=150)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=4)),
                ('value', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RecentSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(max_length=150)),
                ('is_stale', models.BooleanField(default=False)),
                ('etag', models.TextField(max_length=100)),
                ('characters', models.ManyToManyField(to='demo.Character')),
            ],
        ),
    ]
