# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def apply_default_data(apps, schema_editor):
        Configuration = apps.get_model('demo', 'Configuration')
        Configuration.objects.create(
            code="MRV-CALLS",
            description="Amount of calls made to Marvel API",
            value="0"
        )

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_default_data),
    ]